### ISSUE TITLE
DisableTypeCheckGadgetGenerator technique questions

### ISSUE THREAD

**Issue by emmasuki** [med0x2e/GadgetToJScript#3]
Hi,
I see that in generated scripts the logic is:
1) try to deserialize an object generated using DisableTypeCheckGadgetGenerator (https://github.com/med0x2e/GadgetToJScript/blob/5ac70f6149a30652a11b90e48593be0e97c4cd1c/GadgetToJScript/templates/jscript.template#L31) so the stage1 that was built in the main program.
2) if it fails (so Catch), it will run **ms_2** , that was generated by ASurrogateGadgetGenerator.

I did a test removing the stage2 part from the template and from the main, obtaining an output script that should not rely ASurrogateGadgetGenerator. 

this script for me is not working, (may I miss something), but watching at the code seems that the testAssembly is serialized only in the _msStg2 and DisableTypeCheckGadgetGenerator never receive it.

so the question are: 
a) is it only me or the first part of the output script will always fail? or is it intended to launch the 2nd in the try catch? 
b) where is loaded the testAssembly for DisableTypeCheckGadgetGenerator ?

Thanks

**Comment by med0x2e** [comment]
Hi,

a) The first part (stage_1) of the script will trigger DisableTypeCheckGadgetGenerator gadget and disable Type Checks, then throw an exception which need to be handled in order to execute your second gadget of choice which is in this case generated via ASurrogateGadgetGenerator. (ActivitySurrogateSelector)

b) TestAssembly is serialized via _ ASurrogateGadgetGenerator, DisableTypeCheckGadgetGenerator gadget is used only to disable "ActivitySurrogateSelector " type check fixes introduced in .NET 4.8+ (https://github.com/microsoft/dotnet-framework-early-access/blob/master/release-notes/NET48/dotnet-48-changes.md).
